[[redirects]]
  from = "/api"
  to = "http://tennisreservations-env.eba-mtyw5iby.us-east-2.elasticbeanstalk.com/api"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}